### ISSUE TITLE
Latest 1.3 version still unreleased/untagged

### ISSUE THREAD

**Issue by jasonkarns** [brianmario/mochilo#24]
Is there anything blocking the latest of the 1.x release line from being released? (published to rubygems and tagged?)

Latest commit on [v1-release](https://github.com/brianmario/mochilo/tree/v1-release) line is 70afb07b3e984620f3516019e7ee0f85e030ffdd and is showing v1.3.0 (though I believe it should be at least 1.3.1 due to https://github.com/brianmario/mochilo/pull/22)

**Comment by jasonkarns** [comment]
Also, I see that v1.3 itself is tagged in git, but not published to rubygems. Even if 1.3.1 isn't ready for release, it would be helpful if 1.3(.0) is published to rubygems.

**Comment by brianmario** [comment]
Just pushed 1.3.0 to rubygems
