### ISSUE TITLE
Add configurable option for default encoding

### ISSUE THREAD

**Issue by technoweenie** [brianmario/mochilo#4]
If people want to switch from the ruby MessagePack library to Mochilo, the behavior for the existing MessagePack data should stay the same.  MessagePack defaults to UTF-8 for strings, while Mochilo defaults to ASCII.

I'd love to have a configurable default so we can safely move over to Mochilo.
1. Set `Mochilo.default_encoding = UTF-8`.
2. Replace instances of MessagePack with Mochilo.
3. Re-encode with Mochilo so that everything gets tagged with an encoding.  (Optional)
4. Ship MessagePack to the Garbage Planet that JSON is on. Nuke them both until nothing is left.

**Comment by brianmario** [comment]
Mochilo's non-extension string type is used for UTF-8 strings already. The added string types will be used for other encodings. So the encoding should essentially just pass through, not requiring a default be set at the library level.
